### ISSUE TITLE
Sub-structure evaluation 

### ISSUE THREAD

**Issue by GRAPH-0** [pengxingang/Pocket2Mol#13]
Hi, thanks for your nice work!
It seems that the evaluation code for the distributions of bond angles and dihedral angles (Table 3 in the paper) is missing.
Would you mind providing related codes for reproducing? Please let me know if I miss it in the repo.

**Comment by pengxingang** [comment]
Thanks for your interest. The bond angles and dihedral angles can be directly calculated using rdkit package so we did not provide them. But we can also provide them if you need them. We will upload them soon.

**Comment by GRAPH-0** [comment]
Appreciate your quick response and update!

**Comment by pengxingang** [comment]
We have uploaded a file `ring_angle_dihedral.ipynb` to the directory `evaluation` which included the counting of rings, calculation of bond angles, and calculation of dihedral angles. Try it!

**Comment by GRAPH-0** [comment]
Wow! Thanks for your clear codes!
