### ISSUE TITLE
about the KL divergence

### ISSUE THREAD

**Issue by BL-Lac149597870** [pengxingang/Pocket2Mol#15]
Hi, thanks for the awesome works!

I met a problem when caculating the KL divergence of molecular bond angles between training and testing sets. As I noticed that you caculated the KL divergence of the bond angles and dihedral angles with the test set. May I ask you to kindly provide the corresponding codes?

**Comment by pengxingang** [comment]
Thanks for your interest in our work. We uploaded `evaluation/ring_angle_diheral.ipynb` in our last update. It contained the codes about the calculation of KL divergence and the calculation of bond angles and dihedral angles. You can refer to that file and see whether it can solve your problem.

**Comment by BL-Lac149597870** [comment]
Thanks for your reply!  
My confusion is, when caculating KL between P and Q, we always need two discrete probability distributions p_i and q_i. Now I have the dihedral angles, but how can I convert them into discrete probability distributions? As shown in the following, it seems that the scipy api only takes two discrete probability distributions as input.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/31134008/219360181-b7b3e0cc-f233-4dd2-9989-9eec142970e2.png">

**Comment by pengxingang** [comment]
We can discretize the continuous angle values into binned values, just like calculating the empirical distributions. For example, using one degree as the bin width can transfer the angle space into a discrete space with 180 classes.

**Comment by BL-Lac149597870** [comment]
Thanks very much！！！
