### ISSUE TITLE
Is Pocket2Mol able to generate pockets

### ISSUE THREAD

**Issue by MaranathaC** [pengxingang/Pocket2Mol#19]
I am trying to sample for pockets in the testset, but I couldn't find the "crossdocked_pocket10_name2id.pt" file.

My crossdocked_pocket10 and split_by_name.pt are located at /data/

**Comment by pengxingang** [comment]
Hi, the file `crossdocked_pocket10_name2id.pt` is automatically generated by the code. You can just remove the `crossdocked_pocket10_processed.lmdb` and rerun the sampling script. Both the `crossdocked_pocket10_processed.lmdb` and the `crossdocked_pocket10_name2id.py` will be generated.
