### ISSUE TITLE
Question about training time

### ISSUE THREAD

**Issue by schjr** [pengxingang/Pocket2Mol#26]
Hello,
Thank you for your wonderful work! 
I am running Pocket2Mol using a TITAN RTX under the default settings. I notice that my training process is time-consuming (4days).
I wonder how long does it approximately take to train in your experiment, and how many V100s are used.

**Comment by pengxingang** [comment]
Hi, thanks for your interest in our work. We checked the training time. Under the default setting and using one A100 GPU, it takes about 5 days to train Pocket2Mol for 500,000 steps. It's possible to accelerate the training process by using more GPUs and other config settings.

**Comment by schjr** [comment]
I see. Thank you for your reply!
