### ISSUE TITLE
Regarding the evaluation

### ISSUE THREAD

**Issue by SeulLee05** [pengxingang/Pocket2Mol#3]
Hi, thanks for the awesome work.
The code for sampling is provided,
but I guess the evaluation code for Vina score, QED, SA, etc. (i.e., Table 1 of the paper), is missing.
For the reproducibility of your work, may I ask you to kindly include the evaluation code?

**Comment by pengxingang** [comment]
Thanks for your advice! We will consider adding the evaluation code soon.

**Comment by pengxingang** [comment]
We have uploaded the evaluaion code.

**Comment by SeulLee05** [comment]
Thanks a lot for your kind reply!
