### ISSUE TITLE
The loss of MDN is negative

### ISSUE THREAD

**Issue by Saoge123** [pengxingang/Pocket2Mol#4]
非常棒的工作，感谢作者的分享！
有一个问题想请教一下：我用默认的config训练模型（除了pin_memory设置成False），随着训练的进行其中position_predictor的loss变成负数。
所以想问一下是什么原因导致的，是否会影响模型的收敛？
![28175eb763483c3ce303cc3da698196](https://user-images.githubusercontent.com/45249977/180116623-1c7726e8-12ef-4bac-8b7f-e4c704070787.png)

**Comment by pengxingang** [comment]
您好，感谢您对我的工作感兴趣。loss(pos)是预测原子位置的损失函数，而位置的生成是一个混合高斯分布，其损失函数是概率分布的负对数似然，所以可以有正有负，出现负数是正常的。具体计算可以看models/maskfill.py的356行。

Thanks for your interests in my work. Loss(pos) is the loss function of the predicted atom positions. It is modeled as a Gaussian Mixture Model and the loss is the negative log-likelihood. So it is possible to be negative. You can refer to Line 356 of models/maskfill.py for more details.

**Comment by Saoge123** [comment]
I see. Thank you very much for your reply！
