### ISSUE TITLE
Issues about the vina score

### ISSUE THREAD

**Issue by Layne-Huang** [pengxingang/Pocket2Mol#7]
Hi, 

I have used your vina score script "docking.py" recently. However, I have met the following error,

> Traceback (most recent call last):
  File "/sample_geo.py", line 519, in <module>
    g_vina_score = vina_task.run_sync()
  File "/evaluation/docking.py", line 168, in run_sync
    while self.get_results() is None:
  File "/evaluation/docking.py", line 182, in get_results
    self.results = parse_qvina_outputs(self.docked_sdf_path)
  File "/evaluation/docking.py", line 24, in parse_qvina_outputs
    suppl = Chem.SDMolSupplier(docked_sdf_path)
OSError: File error: Invalid input file /tmp/olzbpempbkdjotcpxfbqvwjfnxltvc_ligand_out.sdf

I found that error was caused by the missing script “prepare_receptor4.py ”.

Could you please help me solve it or provide this script? 

Thank you for your attention.

**Comment by pengxingang** [comment]
Hi, to use `docking.py` you should install conda environment defined in `adt.yml`. When you installed the environment, the `prepare_receptor4.py` file were automatically installed. You can check whether you have successfully installed the environment by directly tapping `prepare_receptor4.py` and `qvina2` in the terminal
.
